[loggers]
keys=root

[handlers]
keys=fileHandler

[formatters]
keys=Formatter

[logger_root]
level=INFO
handlers=fileHandler

[handler_fileHandler]
class=FileHandler
formatter=Formatter
args=('logigp2.log','w')

[formatter_Formatter]
format=%(asctime)s %(levelname)s %(message)s